### ISSUE TITLE
Bug: AttributeError in converter.py - 'FreeTypeFont' object has no attribute 'getsize'

### ISSUE THREAD

**Issue by SaltyFishOTL** [ryan4yin/video2chars#12]
**问题：**
在使用 video2chars 进行视频转换时，遇到了以下错误：

> Traceback (most recent call last):
>   File "c:\python38\lib\runpy.py", line 194, in _run_module_as_main
>     ...
> AttributeError: 'FreeTypeFont' object has no attribute 'getsize'

**复现步骤**

1. 安装 video2chars：pip install video2chars
2. 运行 video2chars 进行视频转换。

**期望行为**
视频应该能够正常转换，没有报错。

**实际行为**
遇到 'FreeTypeFont' object has no attribute 'getsize' 错误，导致视频转换失败。

**环境信息**
Python 版本：3.8.8
video2chars 版本：0.6.5
Pillow 版本：10.2.0

**解决方案**
将 converter.py 文件中的如下一行代码：
> self.font_width = sum(self.font.getsize("a")) // 2
修改为：
> self.font_width = sum(self.font.getbbox("a")[2:]) // 2

希望这个修改可以被集成到下一个版本中。

**Comment by ryan4yin** [comment]
Fixed by https://github.com/ryan4yin/video2chars/releases/tag/v0.7.0
